# Development-only services
# Run with: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # pgAdmin for PostgreSQL database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nestjs-pgadmin-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nestjs-network
    profiles:
      - dev-tools

networks:
  nestjs-network:
    external: true
